# Generated by Django 4.1.2 on 2022-11-14 03:27

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=200)),
                ('narasumber', models.CharField(max_length=200)),
                ('lokasi', models.CharField(max_length=300)),
                ('deskripsi', models.TextField()),
                ('tgl_acara', models.DateTimeField()),
                ('tgl_selesai', models.DateTimeField()),
                ('img_event', models.ImageField(blank=True, null=True, upload_to=events.models.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='run_down',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_acara', models.CharField(blank=True, max_length=300, null=True)),
                ('jadwal', models.TimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.myevents')),
            ],
        ),
        migrations.CreateModel(
            name='pickedupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default='9878f364e22449b1845024ae0d99547e')),
                ('status', models.BooleanField(default=False)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.myevents')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='profiles.userprofile')),
            ],
        ),
    ]
