# Generated by Django 4.1.2 on 2022-11-14 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickedupevent',
            name='uid',
            field=models.UUIDField(default='fa2de47508fa44508917be65774bf9a1'),
        ),
        migrations.AlterField(
            model_name='run_down',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rundown', to='events.myevents'),
        ),
    ]
