# Generated by Django 4.1.2 on 2022-11-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_pickedupevent_join_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickedupevent',
            name='uid',
            field=models.UUIDField(default='420f6edf6da0495a93414d910474a6d3'),
        ),
    ]
