# Generated by Django 4.1.2 on 2022-11-15 09:23

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_pickedupevent_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='myevents',
            name='sertifikat',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.path_sertifikat),
        ),
        migrations.AlterField(
            model_name='pickedupevent',
            name='uid',
            field=models.UUIDField(default='9f48b529b32640778cc6bafc64fe3a4b'),
        ),
    ]
