# Generated by Django 4.1.2 on 2022-11-22 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_myevents_sertifikat_alter_pickedupevent_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickedupevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.myevents'),
        ),
        migrations.AlterField(
            model_name='pickedupevent',
            name='uid',
            field=models.UUIDField(default='36057ace31654860877f571dd04ad6d3'),
        ),
    ]
