# Generated by Django 4.1.2 on 2022-11-22 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_pickedupevent_event_alter_pickedupevent_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickedupevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.myevents'),
        ),
        migrations.AlterField(
            model_name='pickedupevent',
            name='uid',
            field=models.UUIDField(default='7d75af0dfced44cd935960e8ac130bfb'),
        ),
    ]
