# Generated by Django 4.1.2 on 2022-11-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_pickedupevent_event_alter_pickedupevent_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickedupevent',
            name='uid',
            field=models.UUIDField(default='677af039680e4a69a1c6da5b328d2db9'),
        ),
    ]
